title: skaigroove's dev archive
author: skaigroove
subtitle: Linux · Network · DevOps 기록

url: "https://skaigroove.github.io"
baseurl: ""

footer_only_homepage: true
footer_url: "https://github.com/skaigroove"
footer_text: "skaigroove @ GitHub"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Tags"
   link: "tags"
